services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gsm-php
    working_dir: /var/www/html
    env_file:
      - .env.docker
    volumes:
      - ./:/var/www/html:delegated
      # var/ sur un volume Linux => writable pour Symfony
      - gsm_var:/var/www/html/var
      - gsm_uploads:/var/www/html/public/uploads
    depends_on:
     mysql:
        condition: service_healthy
     mongo:
        condition: service_healthy

  nginx:
    image: nginx:stable
    container_name: gsm-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # nginx doit aussi voir public/assets + public/build etc
      - gsm_var:/var/www/html/var:ro
      - gsm_uploads:/var/www/html/public/uploads:ro
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: gsm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsm
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 3s
      timeout: 3s
      retries: 30
  mongo:
    image: mongo:6.0
    container_name: gsm-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
volumes:
  mysql_data:
  mongo_data:
  gsm_var:
  gsm_uploads:
